name: Deploy Word Wheel Backend to Raspberry Pi

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'src/**'
      - 'requirements.txt'
      - '.github/workflows/deploy-backend.yaml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        working-directory: ~/wordwheel-solver
        run: |
            git pull origin main
            source venv/bin/activate
            
      - name: Restart Flask wordwheel api
        run: |
            sudo systemctl restart wordwheel-api