name: Deploy Word Wheel Backend to Raspberry Pi

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'src/**'
      - 'requirements.txt'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd ~/wordwheel-solver
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart wordwheel-api